Repository NVIDIA/spark-rapids-examples, pull requests merged in 2022-01, with the labels that each got.

#77 Change signoff check image to slim-buster
  .github/workflows/signoff-check.yml
  .github/workflows/signoff-check/Dockerfile
  .github/workflows/signoff-check/action.yml
  .github/workflows/signoff-check/signoff-check
Labels: bug

#80 cherry pick pr64 databricks docs and init script notebook
  datasets/README.md
  docs/get-started/xgboost-examples/csp/databricks/databricks.md
  docs/get-started/xgboost-examples/csp/databricks/generate-init-script-7.3.ipynb
  docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
  docs/img/databricks/initscript.png
  docs/img/databricks/sparkconfig.png
  examples/Spark-ETL+XGBoost/README.md
Labels: documentation

#83 Reword doc v2202
  README.md
  datasets/README.md
  docs/get-started/xgboost-examples/notebook/python-notebook.md
  docs/get-started/xgboost-examples/notebook/spylon.md
  docs/get-started/xgboost-examples/notebook/toree.md
  docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
  docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md
  docs/get-started/xgboost-examples/on-prem-cluster/standalone-scala.md
  docs/get-started/xgboost-examples/on-prem-cluster/yarn-python.md
  docs/get-started/xgboost-examples/on-prem-cluster/yarn-scala.md
  docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
  docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md
  examples/Spark-ETL+XGBoost/README.md
  examples/Spark-ETL+XGBoost/mortgage/notebooks/python/MortgageETL.ipynb
  examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage-ETL.ipynb
  examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/python/taxi-ETL.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi-ETL.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
  examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
Labels: documentation

#90 Enable auto-merge
  .github/workflows/auto-merge.yml
  .github/workflows/auto-merge/Dockerfile
  .github/workflows/auto-merge/action.yml
  .github/workflows/auto-merge/automerge
Labels: build

#95 Fix non-MIG GPU output ignored
  examples/MIG-Support/yarn-unpatched/README.md
  examples/MIG-Support/yarn-unpatched/scripts/mig2gpu.sh
  examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh
Labels: bug
