Repository NVIDIA/spark-rapids-examples, pull requests merged in 2022-02, with the labels that each got.

#101 Remove link-breaking newline in MIG-Support/README
  examples/MIG-Support/README.md
Labels: bug, documentation

#107 update cudf jni doc from legacy to stable
  examples/RAPIDS-accelerated-UDFs/README.md
Labels: documentation

#106 update doc for rapids v2202 release
  docs/get-started/xgboost-examples/csp/databricks/databricks.md
  docs/get-started/xgboost-examples/csp/databricks/generate-init-script-7.3.ipynb
  docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb
  docs/get-started/xgboost-examples/on-prem-cluster/kubernetes-scala.md
  docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
  docs/get-started/xgboost-examples/prepare-package-data/preparation-scala.md
  examples/Spark-ETL+XGBoost/mortgage/notebooks/python/MortgageETL.ipynb
  examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage-ETL.ipynb
  examples/Spark-ETL+XGBoost/mortgage/notebooks/scala/mortgage_gpu_crossvalidation.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/python/taxi-ETL.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi-ETL.ipynb
  examples/Spark-ETL+XGBoost/taxi/notebooks/scala/taxi_gpu_crossvalidation.ipynb
  examples/Spark-cuML/pca/spark-submit.sh
  examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb
Labels: documentation

#111 Change PCAExample version to 22.04.0-SNAPSHOT
  examples/Spark-cuML/pca/pom.xml
  examples/Spark-cuML/pca/spark-submit.sh
Labels: build

#114 Fix read of mig2gpu.sh on centos 7 and update docs
  examples/MIG-Support/yarn-unpatched/README.md
  examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh
  examples/MIG-Support/yarn-unpatched/scripts/nvidia-smi
Labels: bug

#119 Update for the cudf/rapids v22.02.0 release
  examples/RAPIDS-accelerated-UDFs/README.md
  examples/RAPIDS-accelerated-UDFs/pom.xml
  examples/Spark-cuML/pca/README.md
Labels: documentation, build

#115 Fix read of mig2gpu.sh on centos 7 and update docs
  examples/MIG-Support/yarn-unpatched/README.md
  examples/MIG-Support/yarn-unpatched/scripts/nvidia-container-cli-wrapper.sh
  examples/MIG-Support/yarn-unpatched/scripts/nvidia-smi
Labels: bug
